all: clean

parse:
	python3 cache_wiki.py -p 'Erdős number'



path:
	python3 shortest_path.py -v --from 'Erdős number - Wikipedia' --to 'Alphabet - Wikipedia'


graph:
	python3 render_graph.py


clean:
	rm -rf wiki_graph.png wiki_graph.html wiki.json lib __pycache__ log_file.log
 

